<a href="https://colab.research.google.com/github/wizlearner/vanna/blob/master/ASCII_Canvas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Problem Statement

*** The Problem ***

__Description__

You're given the task of writing a simple console version of a drawing program.
At this time, the functionality of the program is quite limited but this might change in the future.
In a nutshell, the program should work as follows:
 1. Create a new canvas
 2. Create
 3. Quit
Command 		Description
C w h           Should create a new canvas of width w and height h.
L x1 y1 x2 y2   Should create a new line from (x1,y1) to (x2,y2). Currently only
                horizontal or vertical lines are supported. Horizontal and vertical lines
                will be drawn using the 'x' character.
R x1 y1 x2 y2   Should create a new rectangle, whose upper left corner is (x1,y1) and
                lower right corner is (x2,y2). Horizontal and vertical lines will be drawn
                using the 'x' character.
B x y c         Should fill the entire area connected to (x,y) with "colour" c. The
                behavior of this is the same as that of the "bucket fill" tool in paint
                programs.
Q               Should quit the program.

__Sample I/O__

Below is a sample run of the program. User input is prefixed with enter command:



![alt text](https://drive.google.com/open?id=1f95UvF_ZkzZ_xvvzeE7wRxdrf9pC6_i6) Output


## Design Considerations

##*italicized text* Pseudo Code

(i) Create Canvas class: Handle drawing different primitives like pixel, line, rectangle and do a bucket fill. 

(ii) Implement reading commands from console and apply them on a canvas.

(iii) Then print out the canvas on each command.

## Input validation (Don't let the user input invalid values.) 

(i) If your canvas starts at 1, 0 and below should be invalid. 

(ii) And Bucket fill should notify the user in case they fill directly on a line (or outside the canvas).

(iii) Also check if too many or too few arguments were supplied.

Command Line Parser | Validation Support
    ##### HARD Validation Type
          # No Input on CLS Error:Command NotFound
          ## cmdLength !=[3,4,5,1] Error:Incomplete Command
          ### cmdType !=[C,L,R,B,Q] Error:Invalid I/O
    ##### SOFT Validation Type
          # C w h [w,h]!=Int Err:Coordinates/Require Num  
          ## L x y a b CHECK y=b Error: y=b 
          ### R x y a b CHECK x!=a and y!=b 

(iv) Trick to draw the 

(v) Start drawing on the canvas by issuing various commands

(vi) Can the codebased evolve with new requirements

(vii) Testing Cases Class has to be added

(viii) Package in an API/Docker Image Distributable





# Product Release


## Quick Run

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')
##!ls /content/gdrive/My\ Drive/vanna/*.py
##!cat '/content/gdrive/My Drive/vanna/helper.py'

import sys
sys.path.append('/content/gdrive/My Drive/vanna')

!pip install pyfiglet
import pyfiglet
ascii_banner = pyfiglet.figlet_format("VANNA....!!")
print(ascii_banner)


import re
import numpy as np

import draw
import validate
import helper

##------------Main Program------------
# Run count of the game.
#First run set default Values | Avoid in successive runs once Canvas is constructed
run,game_active = 0, True
transdict = {'8': '-', '9' : '|', '1' : 'x','0' : ' ','5' : 'o','7' : '+'} #Translation Dictionary
color_tracker,targetDigit = {},0 

# Set up the while loop.
# At some point, the game ends and game_active will be set to False.
# When that happens, the loop will stop executing.

while game_active:

    # Get some input from the user.
    command = input('enter command: ')
    # This is the command input taken the user
    commandList = (re.split(r'\s',command)) # Separate string by spaces i.e '\s' expression
    print(commandList) 
    print(len(commandList))
    #Empty string Validation needs to be handled as command="" edge case is giving length = 1
    cmdType = commandList[0]
    game_active = validate.commandValidation(len(commandList),cmdType)
    print('You typed a Valid Command')
    
    ## START OF MAIN PROGRAM
    if game_active == 'drawCanvas' and run == 0:
          Canvas1 = draw.drawEmptyCanvas(int(commandList[1]),int(commandList[2]))
          helper.publish(Canvas1, transdict)
          run = run + 1
    elif game_active == 'drawLine': 
          #L 1 3 4 3 [Line Movement on a given Row] OR #L 2 1 2 4 [Line Movement on a given Column]
          ## e.g. L 1 3 4 3 #(x1,x2) = (1,4) & (y1,y2)= (3,3) [On Row 3 draw a line covering 4-1+1 = 4places] = WalkType = AlongRow
          x1,y1 = int(commandList[1]), int(commandList[2])
          x2,y2 = int(commandList[3]), int(commandList[4])
          
          if run == 0:
              print ('Forgot to Draw the Canvas: DRAWING DEFAULT 20 x 20 Canvas')
              Canvas1 = draw.drawEmptyCanvas(20,20)
              helper.publish(Canvas1, transdict)
              print('Since You Forgot we Assumed C 20 20 and created Default Canvas')
              
              Canvas1 = draw.drawLine(Canvas1,x1,y1,x2,y2,maskDigit=1) 
              helper.publish(Canvas1, transdict)
              
              run = run + 1
          
          else:  
              #Using maskDigit=1 means mask by 1 in 2D array  
              Canvas1 = draw.drawLine(Canvas1,x1,y1,x2,y2,maskDigit=1) 
              helper.publish(Canvas1, transdict)
              run = run + 1
    
    elif game_active == 'drawRectangle':
          #R 1 5 6 7[Draw a Rectangle between (1,5) and (6,7)]
          ##Essentially it means draw 4 lines i.e [L 1 5 1 7] [L 6 5 6 7] [L 1 5 6 5] [L 1 7 6 7]
          x1,y1 = int(commandList[1]), int(commandList[2])
          x2,y2 = int(commandList[3]), int(commandList[4])
          
          if run == 0:
             print ('Forgot to Draw the Canvas: DRAWING DEFAULT 20 x 20 Canvas')
             Canvas1 = draw.drawEmptyCanvas(20,20)
             helper.publish(Canvas1, transdict)
             print('Since You Forgot we Assumed C 20 20 and created Default Canvas')
             
             Canvas1 = draw.drawRect(Canvas1,x1,y1,x2,y2,maskDigit=1)
             helper.publish(Canvas1, transdict)

             run = run + 1
          else:
              #Using maskDigit=1 means mask by 1 in 2D array  
              Canvas1 = draw.drawRect(Canvas1,x1,y1,x2,y2,maskDigit=1)
              helper.publish(Canvas1, transdict)
              run = run + 1
    
    elif game_active == 'fillBucket':
          x,y,color = int(commandList[1]), int(commandList[2]), commandList[3]
          print('TIME TO PAINT THE BUCKET with color '+ color)
          maskDigit = 100 - run
    
          color_tracker.update({str(maskDigit):color})
          print(color_tracker) 

          targetDigit = Canvas1[x,y]
          Canvas1 = draw.fillBucket(Canvas1, x, y, targetDigit, maskDigit)
          transdict = helper.updateColor(transdict,color,maskDigit)
          helper.publish(Canvas1, transdict)
          run = run + 1
    else:
          print('YOUR INPUT IS INVALID TRY AGAIN OR PRESS Q TO EXIT')
          run = run + 1     

# Do anything else you want done after the loop runs.
print("\nOh no, you decided to QUIT call coins collected = 0! Game Over.")

##Unit Tests

In [7]:
import unittest

class Expect(unittest.TestCase):

	def length_of_list_to_be_equal(self,length,inputs):
		self.assertEqual(len(inputs), length)

	def values_to_be_equal(self,a,b):
		self.assertEqual(a, b)

expect = Expect()

print("\nUnit Tests\n")


def testDrawLine():
	print(color.BOLD+"> Should Draw a Line"+color.END)
	mockLine = drawLine(1,2,6,2) # Mock
	expect.values_to_be_equal(mockLine,[(1, 2), (2, 2), (3, 2), (4, 2), (5, 2), (6, 2)])

  


Unit Tests



## Single CodeBase

In [1]:
import re
import numpy as np

# Set an initial condition.
game_active = True

#define helper functions
def drawCanvasCMD(cmdType):
        print('Inside drawCanvas' +cmdType)
        if cmdType =='C': 
          return 'drawCanvas'
        else:
          return 'invalid'  

def fillBucketCMD(cmdType):
        print('Inside fillBucket' + cmdType)
        print(cmdType)
        if cmdType =='B':
          return 'fillBucket'
        else:
          return 'Invalid Command' 

def drawLineOrRectangleCMD(cmdType):
        print('Inside drawLineOrRectangleOrfillBucket' + cmdType)
        print(cmdType)
        if cmdType =='L':
          return 'drawLine'
        elif cmdType =='R':
          return 'drawRectangle'
        else:
          return 'invalidCMD'  

def noCommandOrQuittingCMD(cmdType):
        print('Inside noCommandOrQuitting' +cmdType)
        if cmdType =='Q':
          return 'qCMD'
        elif cmdType == ' ':
          return 'noCMD'
        else:
          return 'invalidCMD' 

def noInputCMD(cmdType):
        print('Inside noInput' +cmdType)
        if cmdType == '':
          return 'Nothing entered'
        else:
          return 'invalidCMD' 

def inCompleteCMD(cmdType):
        print('Inside inComplete' +cmdType)
        return 'No Such Command'


def commandValidation(i,cmdType):
        switcher={
                0:noInputCMD,
                1:noCommandOrQuittingCMD,
                2:inCompleteCMD,
                3:drawCanvasCMD,
                4:fillBucketCMD,
                5:drawLineOrRectangleCMD,
                6:lambda:'anything'
                }
        func=switcher.get(i,lambda :'Invalid')      
        return func(cmdType)

def basicHygiene(Canvas,x1,y1,x2,y2):  
        
         #Boundaries of walking to avoid out of bound errors
        canvasWidth = len(Canvas)
        #canvasHeight = len(Canvas[0])
        Canvas.shape
        #print('canvasWidth,canvasHeight=' + str(canvasWidth) + ',' + str(canvasHeight))
        
        #Extra basic Hygiene for a seamless experience
        #Check Canvas is initialized with C x y command if not use default settings 20 x 20
        #Incase the User forgets to create a Canvas, the system Auto Generates is at 20x20 size 
        if (len(Canvas) == 0):
            print('Warning: You forgot to create a Canvas BUT we are kind enough to create DEFAULT 20 x 20')
            Canvas = drawCanvas(20,20) #Run Constructor
        return Canvas 


def drawLine(Canvas,x1,y1,x2,y2, maskDigit):
    Canvas = basicHygiene(Canvas,x1,y1,x2,y2)
    ## Write Validation of Canvas.shape and x1,x2,x3,x4 being within bounds
    #Check basic Geometry Principles to draw a Line atleast y1 = y2 [Horizontal Line]
    if (y1 == y2): 
        ##Return a new 1D array of given shape and type, filled with ones.
        ## Using command  np.ones((x2-x1+1,), dtype=int) 
        ##Using '1' to draw line i.e x2-x1+1 and hence updating entries for columns on a given row
        Canvas[y1, x1:x2+1] = np.ones((x2-x1+1,), dtype=int)*maskDigit ## e.g. Represents [1,1,1,1] if x2-x1+1 = 4
    
    #Check basic Geometry Principles to draw a Line atleast x1=x2 [Vertical Line]
    elif(x1 == x2): 
        ##Return a new 1D array of given shape and type, filled with ones.
        ## Using command  np.ones((y2-y1+1,), dtype=int) 
        ##Using '1' to draw line i.e y2-y1+1 and hence updating entries for rows on a given column
        Canvas[y1:y2+1, x1] = np.ones((y2-y1+1,), dtype=int)*maskDigit  ## e.g. Represents [1,1,1,1] if y2-y1+1 = 4
    
    #Checking for slope 1 or -1 then diagonal is possible in the give 2-D array geometry
    elif((y2-y1)/(x2-x1)== 1 or (y2-y1)/(x2-x1)== -1): 
         Canvas = drawDiagonal(Canvas,x1,y1,x2,y2,maskDigit=7) 
    #Since the input command met basic validation criteria, a rectangle has been requested with L command by mistake
    else:
        print('Drawing a Rectangle with this command is criminal you asked for a line: L but BONUS')
        print ('I will auto update the Command by substituting L with R keeping same cooridnates')
        print('Command Updation with AutoCorrection to R')
        Canvas = drawRect(Canvas,x1,y1,x2,y2,maskDigit=1)
    return Canvas

##Making Diagonal Line Function

def drawDiagonal(Canvas,x1,y1,x2,y2,maskDigit):
    print('---Inside drawDiagonal--')
    print(x1,y1,x2,y2)
    
    Canvas = basicHygiene(Canvas,x1,y1,x2,y2)


    if y2-y1 == 0 or x2-x1 == 0 or x1*x2 == 0 or y1*y2 == 0:   #implies either denominator or numerator is 0
      print('---Inside mn == 0 or md == 0---')
      return

    print(Canvas)

    #Change the digit at Canvas[x][y] to maskDigit 
    Canvas[x1][y1] = maskDigit
    print(Canvas)
    
    if x2-x1 < 0 and (y2-y1)>0:   #leftup or rightdown i.e Quadrant(-,+)
        print('hi1')
        drawDiagonal(Canvas,x1-1,y1+1,x2,y2, maskDigit) 
    if x2-x1 < 0 and (y2-y1)<0:   #rightup or leftdown i.e Quadrant(-,-)
        print('hi2')
        drawDiagonal(Canvas,x1+1,y1-1,x2,y2, maskDigit)
    
    if x2-x1 > 0 and (y2-y1)>0:   #rightup or leftdown i.e Quadrant(+,+)
        print('hi3')
        drawDiagonal(Canvas,x1+1,y1+1,x2,y2, maskDigit) 
    if x2-x1 > 0 and (y2-y1)<0:   #leftup or rightdown i.e Quadrant(+,-)
        print('hi4')
        drawDiagonal(Canvas,x1-1,y1-1,x2,y2, maskDigit)         
    return Canvas

def drawRect(Canvas,x1,y1,x2,y2,maskDigit):
    
    Canvas = basicHygiene(Canvas,x1,y1,x2,y2)
    
    drawLine(Canvas,x1,y1,x1,y2,maskDigit) 
    drawLine(Canvas,x2,y1,x2,y2,maskDigit)
    drawLine(Canvas,x1,y1,x2,y1,maskDigit)
    drawLine(Canvas,x1,y2,x2,y2,maskDigit)
    return Canvas

def drawHorizontalPadding(Canvas,x1,y1,x2,y2,maskDigit):
    #Horizontal Padding with '-'
    drawLine(Canvas,0,0,y2-1,0,maskDigit)
    drawLine(Canvas,0,x2-1,y2-1,x2-1,maskDigit)
    return Canvas
    
def drawVerticalPadding(Canvas,x1,y1,x2,y2,maskDigit):
    #Vertical Padding with '|'
    drawLine(Canvas,0,1,0,x2-2,maskDigit) 
    drawLine(Canvas,y2-1,1,y2-1,x2-2,maskDigit)
    return Canvas    

def replace_with_dict(ar, dic):
    # Extract out keys and values
    k = np.array(list(dic.keys()))
    v = np.array(list(dic.values()))

    # Get argsort indices
    sidx = k.argsort()

    # Drop the magic bomb with searchsorted to get the corresponding
    # places for a in keys (using sorter since a is not necessarily sorted).
    # Then trace it back to original order with indexing into sidx
    # Finally index into values for desired output.
    return v[sidx[np.searchsorted(k,ar,sorter=sidx)]]

def fillBucket(Canvas, x, y, targetDigit, maskDigit):
    # Use the Canvas 2D array and check if the oldDigit at x, y needs to be replacesd
    # The recursive algorithm. Starting at x and y, changes any adjacent
    # digits that match targetDigit and then replace by maskDigit.
    canvasWidth = len(Canvas)
    canvasHeight = len(Canvas[0])
    
    if targetDigit == None:
        targetDigit = Canvas[x][y]

    # Base case. If the current x, y digit is not the targetDigit,
    # then do nothing.
    if Canvas[x][y] != targetDigit:
        return Canvas
    
    # Change the digit at Canvas[x][y] to newDigit 
    Canvas[x][y] = maskDigit

    # Recursive calls. Make a recursive call as long as we are not on the
    # boundary (which would cause an Index Error.)
    if x > 0: # left
        fillBucket(Canvas, x - 1, y, targetDigit, maskDigit)
    if y > 0: # up
        fillBucket(Canvas, x, y - 1, targetDigit, maskDigit) 
    if x < canvasWidth-1: # right
        fillBucket(Canvas, x + 1, y, targetDigit, maskDigit)
    if y < canvasHeight-1: # down
        fillBucket(Canvas, x, y + 1, targetDigit, maskDigit)
    return Canvas

def publish(Canvas, transdict):
    chars_ascii = replace_with_dict(Canvas.astype(str),transdict)
    strings_f = chars_ascii.view('U' + str(chars_ascii.shape[1])).flatten()  
    return print( "\n".join(strings_f))

def updateColor(transdict,color, maskDigit):
    ##search for key:7 replace default colour 'o' with new color
    print(transdict)
    transdict.update({str(maskDigit):color})
    print(transdict)
    return transdict

def drawEmptyCanvas(canvas_w,canvas_h):
    row = canvas_w + 2
    col = canvas_h + 2
    ##Canvas = np.empty([rol,col],dtype=int)
    Canvas = np.zeros((row,col),dtype=int).reshape(row,col)
    ##drawPadding: i.e '----' and '|' on borders. This is a special case of drawRect with edge cases
    ##If user demands 10x16 canvas then 12x18 has be designed to accomodate borders padding
    Canvas = drawHorizontalPadding(Canvas,0,0,row,col,maskDigit=8)
    Canvas = drawVerticalPadding(Canvas,0,0,row,col,maskDigit=9)
    return Canvas


##------------Main Program------------
# Run count of the game.
#First run set default Values | Avoid in successive runs once Canvas is constructed
run,game_active = 0, True
transdict = {'8': '-', '9' : '|', '1' : 'x','0' : ' ','5' : 'o','7' : '+'} #Translation Dictionary
color_tracker,targetDigit = {},0 

# Set up the while loop.
# At some point, the game ends and game_active will be set to False.
# When that happens, the loop will stop executing.
while game_active:

    # Get some input from the user.
    command = input('enter command: ')
    # This is the command input taken the user
    commandList = (re.split(r'\s',command)) # Separate string by spaces i.e '\s' expression
    print(commandList) 
    print(len(commandList))
    #Empty string Validation needs to be handled as command="" edge case is giving length = 1
    cmdType = commandList[0]
    game_active = commandValidation(len(commandList),cmdType)
    print('You typed a Valid Command')
    
    ## START OF MAIN PROGRAM
    if game_active == 'drawCanvas' and run == 0:
          Canvas1 = drawEmptyCanvas(int(commandList[1]),int(commandList[2]))
          publish(Canvas1, transdict)
          run = run + 1
    elif game_active == 'drawLine': 
          #L 1 3 4 3 [Line Movement on a given Row] OR #L 2 1 2 4 [Line Movement on a given Column]
          ## e.g. L 1 3 4 3 #(x1,x2) = (1,4) & (y1,y2)= (3,3) [On Row 3 draw a line covering 4-1+1 = 4places] = WalkType = AlongRow
          x1,y1 = int(commandList[1]), int(commandList[2])
          x2,y2 = int(commandList[3]), int(commandList[4])
          
          if run == 0:
              print ('Forgot to Draw the Canvas: DRAWING DEFAULT 20 x 20 Canvas')
              Canvas1 = drawEmptyCanvas(20,20)
              publish(Canvas1, transdict)
              print('Since You Forgot we Assumed C 20 20 and created Default Canvas')
              
              Canvas1 = drawLine(Canvas1,x1,y1,x2,y2,maskDigit=1) 
              publish(Canvas1, transdict)
              
              run = run + 1
          
          else:  
              #Using maskDigit=1 means mask by 1 in 2D array  
              Canvas1 = drawLine(Canvas1,x1,y1,x2,y2,maskDigit=1) 
              publish(Canvas1, transdict)
              run = run + 1
    
    elif game_active == 'drawRectangle':
          #R 1 5 6 7[Draw a Rectangle between (1,5) and (6,7)]
          ##Essentially it means draw 4 lines i.e [L 1 5 1 7] [L 6 5 6 7] [L 1 5 6 5] [L 1 7 6 7]
          x1,y1 = int(commandList[1]), int(commandList[2])
          x2,y2 = int(commandList[3]), int(commandList[4])
          
          if run == 0:
             print ('Forgot to Draw the Canvas: DRAWING DEFAULT 20 x 20 Canvas')
             Canvas1 = drawEmptyCanvas(20,20)
             publish(Canvas1, transdict)
             print('Since You Forgot we Assumed C 20 20 and created Default Canvas')
             
             Canvas1 = drawRect(Canvas1,x1,y1,x2,y2,maskDigit=1)
             publish(Canvas1, transdict)

             run = run + 1
          else:
              #Using maskDigit=1 means mask by 1 in 2D array  
              Canvas1 = drawRect(Canvas1,x1,y1,x2,y2,maskDigit=1)
              publish(Canvas1, transdict)
              run = run + 1
    elif game_active == 'fillBucket':
          x,y,color = int(commandList[1]), int(commandList[2]), commandList[3]
          print('TIME TO PAINT THE BUCKET with color '+ color)
          maskDigit = 100 - run
    
          color_tracker.update({str(maskDigit):color})
          print(color_tracker) 

          targetDigit = Canvas1[x,y]
          Canvas1 = fillBucket(Canvas1, x, y, targetDigit, maskDigit)
          transdict = updateColor(transdict,color,maskDigit)
          publish(Canvas1, transdict)
          run = run + 1
    elif game_active == 'qCMD' : 
         print('Preparing to Quit the Game')
         game_active = False 
    else:
          print('YOUR INPUT IS INVALID TRY AGAIN OR PRESS Q TO EXIT')
          run = run + 1     

# Do anything else you want done after the loop runs.
print("\nOh no, you decided to QUIT call coins collected = 0! Game Over.")

enter command: Q
['Q']
1
Inside noCommandOrQuittingQ
You typed a Valid Command
Preparing to Quit the Game

Oh no, you decided to QUIT call coins collected = 0! Game Over.


## UnitTests

In [13]:
import unittest	
import numpy as np

class TestDrawings(unittest.TestCase):
      def __init__(self):
        self.w, self.h= 6,6
        
        # Empty Array
        self.arrZ = np.zeros((self.w,self.h), dtype=int).reshape(self.w,self.h)
        
        # Hypoethical: Output HORIZONTAL Drawing 
        self.arrH = np.zeros((self.w,self.h), dtype=int).reshape(self.w,self.h)
        self.arrH[1,1:5] = [1,1,1,1]
        ##print(self.arrH)

        # Hypoethical: Output VERTICAL Drawing 
        self.arrV= np.zeros((self.w,self.h), dtype=int).reshape(self.w,self.h)
        self.arrV[1:5,1] = [1,1,1,1]
        ##print(self.arrV)

        #Hyptothetical: Diagonal Drawing
        self.arrD= np.zeros((self.w,self.h), dtype=int).reshape(self.w,self.h)
        self.arrD[1,1] = 1
        self.arrD[2,2] = 1
        self.arrD[3,3] = 1
        self.arrD[4,4] = 1
        ##print(self.arrD)

        #Hyptothetical: Rectangle Drawing
        self.arrR= np.zeros((self.w,self.h), dtype=int).reshape(self.w,self.h)
        self.arrR[1,1:5] = [1,1,1,1]
        self.arrR[1:5,1] = [1,1,1,1]
        self.arrR[1:5,4] = [1,1,1,1]
        self.arrR[4,1:5] = [1,1,1,1]
        ##print(self.arrR)
      
      def test_drawLine(self,x1,y1,x2,y2,maskDigit=1):
        try:
           if(y1==y2):
              print('DrawLine-Horizontal Test')
              np.testing.assert_array_equal(drawLine(self.arrZ,x1,y1,x2,y2,maskDigit=1), self.arrH)
              res = True
           elif(x1==x2):
              print('DrawLine-Vertical Test')
              np.testing.assert_array_equal(drawLine(self.arrZ,x1,y1,x2,y2,maskDigit=1), self.arrV)
              res = True
           else:
              print('Not arrH or arrV')  
           res = True
        except AssertionError as err:
            print ('\n-----Failed Test: DrawLine-Horizontal/Vertical----')
            res = False
            print(err)
        return res
        

      def test_drawDiagonal(self,x1,y1,x2,y2,maskDigit=7):
          try:
              if(x1==x2 and y1==y2):
                  print('DrawLine-Diagonal Test')
                  np.testing.assert_array_equal(drawDiagonal(self.arrZ,x1,y1,x2,y2,maskDigit), self.arrD)
                  res = True
              else:
                  print('Not Diagonal Inputs')  
                  res = True
          except AssertionError as err:
              print ('\n-----Failed Test: DrawLine-Diagonal----')
              res = False
              print(err)
          return res
        
      def test_drawRect(self,x1,y1,x2,y2,maskDigit=7):
          try:
              if(x1!=x2 and y1!=y2):
                print('DrawRectangle Test')
                np.testing.assert_array_equal(drawRect(self.arrZ,x1,y1,x2,y2,maskDigit), self.arrR)
                res = True
              else:
                print('Not Rectangle Inputs')  
                res = True
          except AssertionError as err:
            print ('\n-----Failed Test: DrawRectangle----')
            res = False
            print(err)
          return res
        

test1 = TestDrawings() 
print('DrawLine-Horizontal test passed ? = '+ str(test1.test_drawLine(1,1,4,1,maskDigit=1))) 
test2 = TestDrawings() 
print('DrawLine-Vertical test passed ? = '+ str(test2.test_drawLine(1,1,1,4,maskDigit=1)))
test3 = TestDrawings() 
print('DrawLine-Diagonal test passed ? = '+ str(test3.test_drawDiagonal(1,1,4,4,maskDigit=7)))
test4 = TestDrawings() 
print('DrawRectangle test passed ? = '+ str(test4.test_drawRect(1,1,4,4,maskDigit=1)) )



DrawLine-Horizontal Test
DrawLine-Horizontal test passed ? = True
DrawLine-Vertical Test
DrawLine-Vertical test passed ? = True
Not Diagonal Inputs
DrawLine-Diagonal test passed ? = True
DrawRectangle Test
DrawRectangle test passed ? = True


#Phase0: Fun Examples

## Ex1: SEXY Char to Pixel: Numpy

In [0]:
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw
import numpy as np

text = "SEXY"
path = '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'
font = ImageFont.truetype(path, 12)

size = font.getsize(text)
img = Image.new("1",size,"black")
draw = ImageDraw.Draw(img)
print(draw)
draw.text((0, 0), text, "white", font)
print(img)
pixels = np.array(img, dtype=np.uint8)
'''numerical data arranged in an array-like structure in Python can 
be converted to arrays through the use of the array() function. 
The most obvious examples are lists and tuples'''
print(pixels)
chars = np.array([' ','#'], dtype="U1")[pixels]
print(chars)
'''VIEW: If you update elements of original array the view(snapshot also
    gets automatically updated'''

strings = chars.view('U' + str(chars.shape[1])).flatten()


''' https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html
Flatten the View i.e A copy of the input array, flattened to one dimension
'''

print( "\n".join(strings))

<PIL.Image.Image image mode=1 size=33x11 at 0x7F2901DBE320>
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0]
 [0 1 1 0 0 0 1 0 0 1 1 0 0 1 0 0 1 1 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0]
 [0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 0 1 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0]
 [0 0 1 1 1 1 0 0 0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 1 1 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0]
 [0 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 1 1 0 0 0 0]]
[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '
  ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '

## Ex2: A-Z Char to Pixel: Numpy


In [0]:
from __future__ import print_function
import string
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw
import numpy as np

def char_to_pixels(text, path='arialbd.ttf', fontsize=14):
    """
    Based on https://stackoverflow.com/a/27753869/190597 (jsheperd)
    """
    font = ImageFont.truetype(path, fontsize) #load the font
    w, h = font.getsize(text)  #calc the size of text in pixels
    h *= 2 
    image = Image.new('L', (w, h), 1)  #create a b/w image
    draw = ImageDraw.Draw(image)
    draw.text((0, 0), text, font=font) #render the text to the bitmap
    arr = np.asarray(image)
    arr = np.where(arr, 0, 1)
    arr = arr[(arr != 0).any(axis=1)]
    return arr

def display(arr):
    result = np.where(arr, '#', ' ')
    print('\n'.join([''.join(row) for row in result]))

for c in string.ascii_uppercase:
    arr = char_to_pixels(
        c, 
        path='/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf', 
        fontsize=9)
    print(arr.shape)
    display(arr)
    print()

##Ex3: Printing Boundaries ['-', '|', '@']
Will also have to increases the size of Canvas by order of two both for the width and the height


In [0]:
loop = [1,2,3,]

print('-'*10)
print('|'*5)
print('@'*3)

for i in loop:
    print('-') 

for i in loop:
    print('|') 

canvas_w = [1,2,3]
canvas_h = [1,2,3,4,5]
''' Determining the Position in 2-D matrix e.g. 3,5 '''

for x in canvas_h: 
    print('@')
    for y in canvas_w:
      print('@'*y)

----------
|||||
@@@
-
-
-
|
|
|
@
@
@@
@@@
@
@
@@
@@@
@
@
@@
@@@
@
@
@@
@@@
@
@
@@
@@@


##Ex4: Slicing 2D Array Example

In [0]:
import numpy as np
X = np.array([[135,30],[35,40],[75,40]])
print(X)
print('Prin------')
Y= X[0,0:2]
print(Y)
print('------')
Z = X[0:2,0]
print(Z)

##Ex5: Pattern Matching using RegEx

In [0]:
import re

list = ["guru99 get", "guru99 give", "guru Selenium"]
for element in list:
    z = re.match("(g\w+)\W(g\w+)", element)
if z:
    print((z.groups()))
    
patterns = ['software testing', 'guru99']
text = 'software testing is fun?'
for pattern in patterns:
    print('Looking for "%s" in "%s" ->' % (pattern, text), end=' ')
    if re.search(pattern, text):
        print('found a match!')
else:
    print('no match')
abc = 'guru99@google.com, careerguru99@hotmail.com, users@yahoomail.com'
emails = re.findall(r'[\w\.-]+@[\w\.-]+', abc)
for email in emails:
    print(email)

Looking for "software testing" in "software testing is fun?" -> found a match!
Looking for "guru99" in "software testing is fun?" -> no match
guru99@google.com
careerguru99@hotmail.com
users@yahoomail.com


Ex5:## FUNNNNN.... :Text to ASCII Art

In [0]:
!pip install pyfiglet
import pyfiglet
ascii_banner = pyfiglet.figlet_format("FUNNNNN....!!")
print(ascii_banner)

 _____ _   _ _   _ _   _ _   _ _   _ _   _         _ _ 
|  ___| | | | \ | | \ | | \ | | \ | | \ | |       | | |
| |_  | | | |  \| |  \| |  \| |  \| |  \| |       | | |
|  _| | |_| | |\  | |\  | |\  | |\  | |\  |_ _ _ _|_|_|
|_|    \___/|_| \_|_| \_|_| \_|_| \_|_| \_(_|_|_|_|_|_)
                                                       



##Ex6: FUNNNN...Turtle graphics for Tk 
https://docs.python.org/2/library/turtle.html

### Turtle 1st Ride

In [0]:
## Turtle for Google Colab notebooks Installation for Google Colab
!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

# Make a Square   
initializeTurtle(initial_speed=2)
bgcolor('white')
color('green')

width (30)
forward(100)
right(90)
forward(100)
right(90)
forward(100)
right(90)
forward(100)
right(90)

width (15)
setx (20)
sety(40)
goto(200,100)

right(90)
forward(50)
left(90)
forward(50)
hideturtle()
showturtle()

ERROR! Session/line number was not unique in database. History logging moved to new session 59
  Created wheel for ColabTurtle: filename=ColabTurtle-2.0.0-cp36-none-any.whl size=4033 sha256=28a3289965cce969b3923f24ef0a0f42cfd01248261d69b7df8b2c44704b1f98
  Stored in directory: /root/.cache/pip/wheels/a8/29/ec/ad346f0042ae467cc74f4378916348faf975b07890651dcae7
Successfully built ColabTurtle


### Turtle complex shape

In [0]:
## Turtle for Google Colab notebooks Installation for Google Colab
!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

# Draw a Complex Shape 
initializeTurtle(initial_speed=10)
color('orange')
bgcolor('white')
width(1)
for i in range(36):
    forward(200)
    left(170)

###Turtle: Draw a Tree

In [0]:
## Turtle for Google Colab notebooks Installation for Google Colab
!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

# Draw a Tree

initializeTurtle(initial_speed=10)
color('white')
bgcolor('black')

min_length=20

def draw_branch(l, w):
  left(15)
  draw_stick(l, w)
  right(30)
  draw_stick(l, w)
  left(15)
  
def draw_stick(l, w):
  width(w)
  forward(l)
  if min_length < l:
    draw_branch(math.ceil(l*0.8), math.ceil(w*0.6))
  backward(l)

penup()
sety(470)
pendown()
draw_branch(100, 10)

KeyboardInterrupt: ignored

### Turtle: Triangle/Square

In [0]:
## Turtle for Google Colab notebooks Installation for Google Colab
!pip3 install ColabTurtle
from ColabTurtle.Turtle import *

# User selects which shape to Draw [Triangle/Square]
initializeTurtle(initial_speed=10)
def draw(running, entered):
  initializeTurtle(initial_speed=10)
  while running:
    if entered == 'triangle':
      for i in range(3):
        forward(100)
        right(120)  
      running = False
    elif entered == 'square':
      for i in range(4):
        forward(100)
        right(90)
      running = False
    elif entered == 'exit':
      running = False
      print('exiting...')

    else:
      print('not a command')
  
  
  print('bye!')
  
print('enter triangle, square, or exit:') #supported inputs = {triangle, square, exit}
draw(True, input()) 

### Turle: Draw Line

In [0]:
initializeTurtle(initial_speed=10)
x1, y1, x2, y2 = 10, 20, 30, 40
color('white')
bgcolor('black')

#Vertical Line
forward(x2-x1)

right(90)
#Horizontal Line
forward(y2-y1)

#Phase 1: Quick Prototype

###Step1: Command Line Regex

In [0]:
#import regex library in python
import re

#---------STEPA---------
# ALTERNATE0: Manually hard code assume this is the command input taken the user
command = "C 4 8"

 # ALTERNATE1: Get some input from the user.
command = input('enter command: ')


#---------STEPB---------    
# Separate string by spaces i.e '\s' expression
commandList = re.split(r'\s',command)
print(commandList) 
print(len(commandList))

print('cmd type : ' + commandList[0])
print('canvas_w : ' + commandList[1])
print('canvas_h : ' + commandList[2])


enter command: C 7 8
['C', '7', '8']
3
cmd type : C
canvas_w : 7
canvas_h : 8


###Step2: Canvas as a 2D array


In [0]:
# 3 Simple ways of creating 2D array to represent a Canvas mathematically
import numpy as np

# C 4 8
canvas_w = 4
canvas_h = 8

#ALTERNATE0: Manually hard coding the 2D array will get us going quickly
canvasManual = np.array([[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]])
print(canvasManual)

print('----BREAK----')

#ALTERNATE1: Generating an array of random integers, declaring & populating 2D array
maskDigit=0
canvasManual1 = np.random.randint(0,2, size=(canvas_w,canvas_h))*maskDigit
print(canvasManual1)

print('----BREAK----')

#ALTERNATE2: Using numpy library with method zeros
canvasManual2 = np.zeros((canvas_w,canvas_h), dtype=int).reshape(canvas_w,canvas_h)
print(canvasManual2)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
----BREAK----
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
----BREAK----
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


###Step3: Drawing a Horizontal Line

In [0]:
#e.g Draw Horizontal Line of length 4
# draw from (x1,y1 to x2,y2) WHERE y1 = 2 (i.e x1=1 y1=1 x2=4 y2=1)

##-------ALTERNATE0----------
#Manually hard coding the 2D array will get us going quickly
canvasManual = np.array([[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]])
print(canvasManual)
print('----Before/After----')
canvasManual = np.array([[0,0,0,0,0,0,0],[0,1,1,1,1,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]])
print(canvasManual)

print('----ALTERNATE0: BREAK----')

##-------ALTERNATE1----------
#Return a new 1D array of given shape and type, filled with ones.
canvasManual1 = np.random.randint(0,2, size=(canvas_w,canvas_h))*0 #maskDigit=0
print(canvasManual1)
print('----Before/After----')
#Using slicing updating the Canvas
canvasManual1[1,1:5] = [1,1,1,1]
print(canvasManual1)

print('----ALTERNATE1: BREAK----')

##-------ALTERNATE2----------
#Using numpy library with method zeros
canvasManual2 = np.zeros((4,8), dtype=int).reshape(4,8)
print(canvasManual2)
print('----Before/After----')

x1,y1,x2,y2 = 1,1,4,1
# Using command  np.ones((x2-x1+1,), dtype=int) to create a 1D array from numpy
#Using '1' to draw line i.e x2-x1+1 and hence updating entries for columns on a given row
canvasManual2[y1, x1:x2+1] = np.ones((x2-x1+1,), dtype=int) ## e.g. Represents [1,1,1,1] if x2-x1+1 = 4
print(canvasManual2)
print('----ALTERNATE2: BREAK----')

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
----Before/After----
[[0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
----ALTERNATE0: BREAK----
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
----Before/After----
[[0 0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
----ALTERNATE1: BREAK----
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
----Before/After----
[[0 0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
----ALTERNATE2: BREAK----


###Step4: Translation & Publish

In [0]:
# For now let's manually assume the drawing already happened
canvasManualDraw1 = np.array([[0,0,0,0,0,0,0],[0,1,1,1,1,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]])
print(canvasManualDraw1)

#Convert the '0' and '1' by creating a new array of data type U1 from int32
chars_ascii = np.array(['.','x'], dtype="U1")[canvasManualDraw1]
print(chars_ascii)

print('----BREAK----')

#Use flatten, shape and view methods from numpy to create a string output
strings_f = chars_ascii.view('U' + str(chars_ascii.shape[1])).flatten()
print( "\n".join(strings_f))

print('----ALTERNATE0: BREAK----')




[[0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
----BREAK----
[['.' '.' '.' '.' '.' '.' '.']
 ['.' 'x' 'x' 'x' 'x' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.']]
----BREAK----
.......
.xxxx..
.......
.......


### Step5: Draw a Vertical Line

In [0]:
#Only slicing style will change and we will overwrite the previous Canvas

#ALTERNATE0: Manually hard coding helps in understanding the logic
canvasManualDraw1 = np.array([[0,0,0,0,0,0,0],[0,1,1,1,1,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]])
print(canvasManualDraw1)

print('----Before/After----')

#Using slicing updating the Canvas
canvasManualDraw2[0:4,1] = [1,1,1,1]
print(canvasManualDraw2)

print('----#ALTERNATE0: Completed ----')

#ALTERNATE1: Manually hard coding helps in understanding the logic

print(canvasManualDraw1)

print('----Before/After----')

x1,y1,x2,y2 = 1,0,1,3
##Return a new 1D array of given shape and type, filled with ones.
## Using command  np.ones((y2-y1+1,), dtype=int) 
##Using '1' to draw line i.e y2-y1+1 and hence updating entries for rows on a given column
canvasManualDraw2[y1:y2+1, x1] = np.ones((y2-y1+1,), dtype=int)  ## e.g. Represents [1,1,1,1] if y2-y1+1 = 4
print(canvasManualDraw2)

print('----#ALTERNATE1: Completed ----')

[[0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
----Before/After----
[[0 1 0 0 0 0 0]
 [0 1 1 1 1 0 0]
 [0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0]]
----#ALTERNATE0: Completed ----
[[0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
----Before/After----
[[0 1 0 0 0 0 0]
 [0 1 1 1 1 0 0]
 [0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0]]
----#ALTERNATE1: Completed ----


### Step6: Stitch is all together

In [0]:
import numpy as np

## Command A: Draw a Canvas Taking user input from Command Line
commandA = input('enter commandA: ')
commandListA = re.split(r'\s',commandA)
print(commandListA)
cmdType, canvasW,canvasH = commandListA[0],int(commandListA[1]),int(commandListA[2])
myCanvas = np.zeros((canvasW,canvasH), dtype=int).reshape(canvasW,canvasH)
print(myCanvas)

## Command B: Draw a Horizontal Line
commandB = input('enter commandB: ')
commandListB = re.split(r'\s',commandB)
print(commandListB)
x1,y1,x2,y2 = int(commandListB[1]),int(commandListB[2]),int(commandListB[3]),int(commandListB[4])
myCanvas[y1, x1:x2+1] = np.ones((x2-x1+1,), dtype=int)

chars_ascii1 = np.array(['.','x'], dtype="U1")[myCanvas]
print(chars_ascii1)
print('----BREAK: before/after----')
strings_f = chars_ascii1.view('U' + str(chars_ascii1.shape[1])).flatten()
print( "\n".join(strings_f))

## Command C: Draw a Vertical Line
commandC = input('enter commandC: ')
commandListC = re.split(r'\s',commandC)
x1,y1,x2,y2 = int(commandListC[1]),int(commandListC[2]),int(commandListC[3]),int(commandListC[4])
myCanvas[y1:y2+1, x1] = np.ones((y2-y1+1,), dtype=int)

chars_ascii2 = np.array(['.','x'], dtype="U1")[myCanvas]
print(chars_ascii2)
print('----BREAK: before/after----')
strings_f = chars_ascii2.view('U' + str(chars_ascii2.shape[1])).flatten()
print( "\n".join(strings_f))

#Try the 3 Command Sets for Testing

#CommandA     C 4 8
#CommandB     L 1 1 4 1
#CommandC     L 1 0 1 3

#CommandA     C 20 20
#CommandB     L 1 7 4 7
#CommandC     L 10 0 10 3

#CommandA     C 12 15
#CommandB     L 1 10 4 10
#CommandC     L 5 0 5 6



enter commandA: C 12 15
['C', '12', '15']
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
enter commandB: L 1 10 4 10
['L', '1', '10', '4', '10']
[['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 

#Phase 2: Command Validation
  


## Step1: Switcher for cmdTypes

In [0]:


#Alternate0
def commandValidation(i,cmdType):
        switcher={
                0:noInput,
                1:noCommandOrQuitting,
                2:inComplete,
                3:drawCanvas,
                4:inComplete,
                5:drawLineOrRectangleOrfillBucket,
                6:lambda:'anything'
                }
        func=switcher.get(i,lambda :'Invalid')
        return func(cmdType)

commandValidation(len(commandList),commandList[0])

print('-------BREAK-------')

#Alternate1
method =['Nothing,Canvas,Line,Rectangle,FillBucket,Quit','Inavlid']

class Switcher(object):
          def commandLength(self,i):
                   method_name='draw'+str(i)
                   method=getattr(self,method_name,lambda :'Invalid')
                   return method()
          def draw0(self):
                   return 'noInput'
          def draw1(self):
                   return 'noCommandOrQuitting'
          def draw2(self):
                   return 'inComplete'
          def draw3(self):
                   return 'drawCanvas'
          def draw4(self):
                   return 'inComplete'
          def draw5(self): 
                   return 'drawLineOrRectangleOrfillBucket'
          def draw6(self): 
                   return 'Undefined command of greater than size 6'

s= Switcher()
s.commandLength(len(commandList))

Inside drawLineOrRectangleOrfillBucketL
L
-------BREAK-------


'drawLineOrRectangleOrfillBucket'

## Step2: Handling Different cmdTypes

In [0]:
import re
xx = "L 4 5 6 8"
yy = input()


commandList = (re.split(r'\s',xx)) # Separate string by spaces i.e '\s' expression
print(commandList) 
length = len(commandList)
print(length)
#Empty string Validation needs to be handled as xx="" edge case is giving length = 1

def drawCanvas(cmdType):
        print('Inside drawCanvas' +cmdType)
        if cmdType =='C':
          return 'drawCanvas'
        else:
          return 'Invalid'  

def drawLineOrRectangleOrfillBucket(cmdType):
        print('Inside drawLineOrRectangleOrfillBucket' + cmdType)
        print(cmdType)
        if cmdType =='L':
          return 'drawLine'
        elif cmdType =='R':
          return 'drawRectangle'
        elif cmdType =='B':
          return 'fillBucket'  
        else:
          return 'Invalid Command' 

def noCommandOrQuitting(cmdType):
        print('Inside noCommandOrQuitting' +cmdType)
        if cmdType =='Q':
          return 'quitting'
        elif cmdType == ' ':
          return 'No Command'
        else:
          return 'Invalid Command' 

def noInput(cmdType):
        print('Inside noInput' +cmdType)
        if cmdType == '':
          return 'Nothing entered'
        else:
          return 'Invalid Command'

def inComplete(cmdType):
        print('Inside inComplete' +cmdType)
        return 'No Such Command'


def commandValidation(i,cmdType):
        switcher={
                0:noInput,
                1:noCommandOrQuitting,
                2:inComplete,
                3:drawCanvas,
                4:inComplete,
                5:drawLineOrRectangleOrfillBucket,
                6:lambda:'anything'
                }
        func=switcher.get(i,lambda :'Invalid')
        return func(cmdType)

commandValidation(len(commandList),commandList[0])

C 4 5
['L', '4', '5', '6', '8']
5
Inside drawLineOrRectangleOrfillBucketL
L


'drawLine'

#Phase3: Upgrade Drawing Definitions

##Step1: 2D Array to Desired O/p

In [0]:
chars_ascii = np.array(['.','x'], dtype="U1")[canvasManualDraw2]
strings_f = chars_ascii.view('U' + str(chars_ascii.shape[1])).flatten()
print( "\n".join(strings_f))

..x....
.xxxx..
..x....
..x....


In [0]:
import numpy as np
pixels_01 = np.array([[0,1,0,1,1,1,0],[0,0,0,1,1,0,1],[0,0,0,1,1,0,1],[0,0,0,1,1,0,1]])


canvas_w=3
canvas_h=4


## Generating an array of random integers, declaring & populating 2D array
pixels_01 = np.random.randint(0,2, size=(canvas_w+2,canvas_h+2))
## After adding canvas_w+2,canvas_h+2 we are able to accomdate a border of canvas

## Filling border pads with horizontal '-' and vertical ='|' as directed

print(pixels_01)
print('-------Break-----')
chars_ascii = np.array([' ','#'], dtype="U1")[pixels_01]
print(chars_ascii)
strings_f = chars_ascii.view('U' + str(chars_ascii.shape[1])).flatten()
print('-------Break-----')
print( "\n".join(strings_f))

print('-------Break-----')
print('-------Manually Refilling the Bucket-----')
## Rerun After Manually Refilling the Full Bucket

##pixels_01 = np.array([[1,1,1,1,1,1,1],[1,1,1,1,1,1,1],[1,1,1,1,1,1,1],[1,1,1,1,1,1,1]])
pixels_01 = np.random.randint(1,2, size=(4,8))
chars_ascii = np.array([' ','#'], dtype="U1")[pixels_01]
strings_f = chars_ascii.view('U' + str(chars_ascii.shape[1])).flatten()
print( "\n".join(strings_f))



[[1 0 1 1 1 1 0 1]
 [0 0 0 0 1 1 0 1]
 [1 1 1 1 1 1 1 0]
 [1 1 0 0 1 0 1 1]]
-------Break-----
[['#' ' ' '#' '#' '#' '#' ' ' '#']
 [' ' ' ' ' ' ' ' '#' '#' ' ' '#']
 ['#' '#' '#' '#' '#' '#' '#' ' ']
 ['#' '#' ' ' ' ' '#' ' ' '#' '#']]
-------Break-----
# #### #
    ## #
####### 
##  # ##
-------Break-----
-------Manually Refilling the Bucket-----
########
########
########
########


##Step2: Reshape 1D to 2D array 

In [17]:
import numpy as np


##Canvas requested 3x4--->after Padding--->becomes 5x6 i.e [3+2, 4+2] or [row+2, col+2]
print(np.arange(5*6))

print('-----before/after-----')

#Reshape a shape-(24,) array into a shape-(2,3,4) array
a = np.arange(2*3*4)
print(a)

print('-----before/after-----')
a= np.arange(2*3*4).reshape(6,4)
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
-----before/after-----
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
-----before/after-----
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


##Step3: DrawLine Horizontally

In [16]:
#L 1 3 4 3 [Line Movement on a given Row]
a = np.arange(8*9).reshape(8,9)

COLi = 1
COLj = 4
ROW = 3
#MoveForward: Replace '0s' with '1'


##Return a new array of given shape and type, filled with ones.
array_ones = np.ones((COLj-COLi+1,), dtype=int) ## e.g. Represents [1,1,1,1] if COLj-COLi+1 = 4
##Using '1' to represent forward traversal and hence updating entries
a[ROW, COLi:COLj+1] = array_ones  
print(a)

print('---BREAK---')

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27  1  1  1  1 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]
---BREAK---


##Step4: DrawLine Vertical(Transpose)

In [14]:
b = np.arange(8*9).reshape(8,9) ## Canvas 6x7
#L 2 1 2 4 [Line Movement on a given Column]
ROWi = 1
ROWj = 4
COL = 2
#MoveForward: Replace '0s' with '1'
b[ROWi:ROWj+1, COL ] =  np.ones((ROWj,), dtype=int) ## [1,1,1]
b
print(b)


print('---CHECKING Transpose of a 2D matrix to leverage same code---')
c = np.transpose(a)

##Return a new array of given shape and type, filled with ones.
array_ones_c = np.ones((COLj-COLi+1,), dtype=int) ## e.g. Represents [1,1,1,1] if COLj-COLi+1 = 4
##Using '1' to represent forward traversal and hence updating entries
c[ROW, COLi:COLj+1] = array_ones_c  
print(np.transpose(c))

#We have proven transposing works for Horizontal/Vertical Function. Hence we leverage a standard function


def drawLine(Canvas,x1,y1,x2,y2,maskDigit):
    ## Write Validation of Canvas.shape and x1,x2,x3,x4 being within bounds
    if (y1 == y2): 
        ##Return a new 1D array of given shape and type, filled with ones.
        ## Using command  np.ones((x2-x1+1,), dtype=int) 
        ##Using '1' to draw line i.e x2-x1+1 and hence updating entries for columns on a given row
        Canvas[y1, x1:x2+1] = np.ones((x2-x1+1,), dtype=int)*maskDigit ## e.g. Represents [1,1,1,1] if x2-x1+1 = 4
    elif(x1 == x2): 
        ##Return a new 1D array of given shape and type, filled with ones.
        ## Using command  np.ones((y2-y1+1,), dtype=int) 
        ##Using '1' to draw line i.e y2-y1+1 and hence updating entries for rows on a given column
        Canvas[y1:y2+1, x1] = np.ones((y2-y1+1,), dtype=int)*maskDigit  ## e.g. Represents [1,1,1,1] if y2-y1+1 = 4
    else:
        print('Cant draw a diagonal(out of scope)')
    return Canvas

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10  1 12 13 14 15 16 17]
 [18 19  1 21 22 23 24 25 26]
 [27 28  1 30 31 32 33 34 35]
 [36 37  1 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]
---CHECKING Transpose of a 2D matrix to leverage same code---
[[ 0  1  2  3]
 [ 4  5  6  1]
 [ 8  9 10  1]
 [12 13 14  1]
 [16 17 18  1]
 [20 21 22 23]]


##Step5: DrawLine & Boundary

In [38]:
print('---BREAK0---')

def drawLine(Canvas,x1,y1,x2,y2,maskDigit):
    ## Write Validation of Canvas.shape and x1,x2,x3,x4 being within bounds
    if (y1 == y2): 
        ##Return a new 1D array of given shape and type, filled with ones.
        ## Using command  np.ones((x2-x1+1,), dtype=int) 
        ##Using '1' to draw line i.e x2-x1+1 and hence updating entries for columns on a given row
        Canvas[y1, x1:x2+1] = np.ones((x2-x1+1,), dtype=int)*maskDigit ## e.g. Represents [1,1,1,1] if x2-x1+1 = 4
    elif(x1 == x2): 
        ##Return a new 1D array of given shape and type, filled with ones.
        ## Using command  np.ones((y2-y1+1,), dtype=int) 
        ##Using '1' to draw line i.e y2-y1+1 and hence updating entries for rows on a given column
        Canvas[y1:y2+1, x1] = np.ones((y2-y1+1,), dtype=int)*maskDigit  ## e.g. Represents [1,1,1,1] if y2-y1+1 = 4
    else:
        print('Cant draw a diagonal(out of scope)')
    return Canvas

def drawHorizontalPadding(Canvas,x1,y1,x2,y2,maskDigit):
    #Horizontal Padding with '-'
    drawLine(Canvas,0,0,y2-1,0,maskDigit)
    drawLine(Canvas,0,x2-1,y2-1,x2-1,maskDigit)
    return Canvas
    
def drawVerticalPadding(Canvas,x1,y1,x2,y2,maskDigit):
    #Vertical Padding with '|'
    drawLine(Canvas,0,1,0,x2-2,maskDigit) 
    drawLine(Canvas,y2-1,1,y2-1,x2-2,maskDigit)
    return Canvas    


# Create an Empty 2D Array
Canvas1 = np.zeros((12,18), dtype=int).reshape(12,18)

print(Canvas1)
print('---BREAK0---')
##drawPadding: i.e '----' and '|' on borders. This is a special case of drawRect with edge cases
##If user demands 10x16 canvas then 12x18 has be designed to accomodate borders padding
Canvas1 = drawHorizontalPadding(Canvas1,0,0,12,18,maskDigit=8)
print(Canvas1)
print('---BREAK1---')

Canvas1 = drawVerticalPadding(Canvas1,0,0,12,18,maskDigit=9)
print(Canvas1)
print('---BREAK2---')
#L 1 3 4 3 [Line Movement on a given Row]
#(x1,x2) = (1,4) & (y1,y2)= (3,3) [On Row 3 draw a line covering 4-1+1 = 4places] = WalkType = AlongRow
Canvas1 = drawLine(Canvas1,1,3,4,3,maskDigit=1)
#L 2 1 2 4 [Line Movement on a given Column]
#(y1,y2) = (1,4) & (x1,x2)= (2,2)[On COL 2 draw a line covering 4-1+1 = 4places] = WalkType = AlongCol
print(Canvas1)
print('---BREAK3---')
Canvas1 = drawLine(Canvas1,2,1,2,4,maskDigit=1)
#END RESULT WILL HAVE DIGITS '8' and '9' in the FINAL OUTPUT


---BREAK0---
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
---BREAK0---
[[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]]
---BREAK1---
[[8 8 8 8 8 8 8 8 8 8 8

##Step6: Draw Rectangle

In [152]:
import numpy as np

def drawRect(Canvas,x1,y1,x2,y2,maskDigit):
    drawLine(Canvas,x1,y1,x1,y2,maskDigit) 
    drawLine(Canvas,x2,y1,x2,y2,maskDigit)
    drawLine(Canvas,x1,y1,x2,y1,maskDigit)
    drawLine(Canvas,x1,y2,x2,y2,maskDigit)
    return Canvas

## START OF MAIN PROGRAM

# Create an Empty 2D Array
Canvas1 = np.zeros((12,18), dtype=int).reshape(12,18)
print(Canvas1)
print('---BREAK0---')

#R 1 5 6 7[Draw a Rectangle between (1,5) and (6,7)]
##Essentially it means draw 4 lines i.e [L 1 5 1 7] [L 6 5 6 7] [L 1 5 6 5] [L 1 7 6 7]
print(Canvas1)
print('---BREAK4---')
Canvas1 = drawRect(Canvas1,1,5,6,7,maskDigit=1)
print(Canvas1)
print('---BREAK5---')

print('---1st PUBLISH---')

Canvas1 = drawRect(Canvas1,6,6,8,8,maskDigit=1)
print(Canvas1)
print('---2nd PUBLISH---')





[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
---BREAK0---
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
---BREAK4---
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

##Step7: Fill Bucket

In [24]:
def fillBucket(Canvas, x, y, targetDigit, newDigit):
    # Use the Canvas 2D array and check if the oldDigit at x, y needs to be replacesd
    # The recursive algorithm. Starting at x and y, changes any adjacent
    # digits that match targetDigit to newDigit.
    canvasWidth = len(Canvas)
    canvasHeight = len(Canvas[0])
    
    if targetDigit == None:
        targetDigit = Canvas[x][y]

    # Base case. If the current x, y digit is not the targetDigit,
    # then do nothing.
    if Canvas[x][y] != targetDigit:
        return 
    
    # Change the digit at Canvas[x][y] to newDigit 
    Canvas[x][y] = newDigit

    # Recursive calls. Make a recursive call as long as we are not on the
    # boundary (which would cause an Index Error.)
    if x > 0: # left
        fillBucket(Canvas, x - 1, y, targetDigit, newDigit)
    if y > 0: # up
        fillBucket(Canvas, x, y - 1, targetDigit, newDigit) 
    if x < canvasWidth-1: # right
        fillBucket(Canvas, x + 1, y, targetDigit, newDigit)
    if y < canvasHeight-1: # down
        fillBucket(Canvas, x, y + 1, targetDigit, newDigit)
    return Canvas

## START OF MAIN PROGRAM

# Create an Empty 2D Array
Canvas1 = np.zeros((12,18), dtype=int).reshape(12,18)
print(Canvas1)
print('---BREAK0---')


#User Gives Input
x,y = 2,5 ## [Point of Click, taken from user as input]
#Set the Point of Click for 'o' masked by Digit '5' 

## Now fill the Bucket from here with Digit 5
print('---PUBLISH AFTER Fill Bucket--')
print(fillBucket(Canvas1, x, y, 0, 5))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
---BREAK0---
---PUBLISH AFTER Fill Bucket--
[[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]]


##Step8: Publish Output 

In [26]:
def publish(Canvas):
    transdict = {'8': '-', '9': '|', '1': 'x','0':'.','5':'o'} #Translation Dictionary
    chars_ascii = replace_with_dict(Canvas.astype(str),transdict)
    strings_f = chars_ascii.view('U' + str(chars_ascii.shape[1])).flatten()  
    return print( "\n".join(strings_f))

def replace_with_dict(ar, dic):
    # Extract out keys and values
    k = np.array(list(dic.keys()))
    v = np.array(list(dic.values()))

    # Get argsort indices
    sidx = k.argsort()

    # Drop the magic bomb with searchsorted to get the corresponding
    # places for a in keys (using sorter since a is not necessarily sorted).
    # Then trace it back to original order with indexing into sidx
    # Finally index into values for desired output.
    return v[sidx[np.searchsorted(k,ar,sorter=sidx)]]

## START OF MAIN PROGRAM

# Create an Empty 2D Array
Canvas1 = np.zeros((12,18), dtype=int).reshape(12,18)
print(Canvas1)
print('---BREAK0---')

#User Gives Input
x,y = 2,5 ## [Point of Click, taken from user as input]
#Set the Point of Click for 'o' masked by Digit '5' 

## Now fill the Bucket from here with Digit 5
print('---PUBLISH AFTER Fill Bucket--')
publish(fillBucket(Canvas1, x, y, 0, 5))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
---BREAK0---
---PUBLISH AFTER Fill Bucket--
oooooooooooooooooo
oooooooooooooooooo
oooooooooooooooooo
oooooooooooooooooo
oooooooooooooooooo
oooooooooooooooooo
oooooooooooooooooo
oooooooooooooooooo
oooooooooooooooooo
oooooooooooooooooo
oooooooooooooooooo
oooooooooooooooooo


##Step8: Draw Diagonal

In [8]:
##Drawing Diagonal Line 

def drawDiagonal(Canvas,x1,y1,x2,y2,maskDigit):
    print('---Inside drawDiagonal--')
    
    #Boundaries of walking to avoid out of bound errors
    canvasWidth = len(Canvas)
    canvasHeight = len(Canvas[0])
    
    #determine the slope of the diagonal
    mn = y2-y1  
    md = x2-x1
    print('mn,md' + str(mn) +','+ str(md))

    ##if mn == md: #implies diagonal completed
    ##return
    if y2-y1 == 0 or x2-x1 == 0 or x1*x2 == 0 or y1*y2 == 0:   #implies either denominator or numerator is 0
      print('---Inside mn == 0 or md == 0---')
      return 

     # Change the digit at Canvas[x][y] to newDigit 
    Canvas[x1][y1] = maskDigit
    print(Canvas)
    
    if x2-x1 < 0 and (y2-y1)>0:   #leftup or rightdown i.e Quadrant(-,+)
        print('hi1')
        drawDiagonal(Canvas,x1-1,y1+1,x2,y2, maskDigit) 
    if x2-x1 < 0 and (y2-y1)<0:   #rightup or leftdown i.e Quadrant(-,-)
        print('hi2')
        drawDiagonal(Canvas,x1+1,y1-1,x2,y2, maskDigit)
    
    if x2-x1 > 0 and (y2-y1)>0:   #rightup or leftdown i.e Quadrant(+,+)
        print('hi3')
        drawDiagonal(Canvas,x1+1,y1+1,x2,y2, maskDigit) 
    if x2-x1 > 0 and (y2-y1)<0:   #leftup or rightdown i.e Quadrant(+,-)
        print('hi4')
        drawDiagonal(Canvas,x1-1,y1-1,x2,y2, maskDigit)         
    return Canvas


# Create an Empty 2D Array
Canvas1 = np.zeros((12,18), dtype=int).reshape(12,18)
print(Canvas1)
print('---BREAK0---')
drawDiagonal(Canvas1,3,2,11,10,7)
print('---After completing drawDiagonal--')

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
---BREAK0---
---Inside drawDiagonal--
mn,md8,8
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
hi3
---Inside d

##Step9:  Fill Holes

In [33]:
import numpy as np
from scipy import ndimage

a = np.zeros((5, 5), dtype=int)
a[1:4, 1:4] = 1
a[2,2] = 0
print('---BREAK0---')
print(a)

"""array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])"""

ndimage.binary_fill_holes(a).astype(int)
print('---BREAK1---')
print(a)
"""array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])"""
# Too big structuring element
ndimage.binary_fill_holes(a, structure=np.ones((5,5))).astype(int)
"""array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])"""
print('---BREAK2---')
print(a)


---BREAK0---
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
---BREAK1---
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
---BREAK2---
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [8]:
import numpy as np

a = np.zeros((5, 5), dtype=int)
a[1:4, 1:4] = 1
a[2,2] = 0
a

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [36]:
import numpy as np



## from helper import publish, replace_with_dict, update_color
def publish(Canvas):
    transdict = {'8': '-', '9': '|', '1': 'x','0':'.','5':'o'} #Translation Dictionary
    chars_ascii = replace_with_dict(Canvas.astype(str),transdict)
    strings_f = chars_ascii.view('U' + str(chars_ascii.shape[1])).flatten()  
    opt = "\n".join(strings_f)
    return opt

def replace_with_dict(ar, dic):
    # Extract out keys and values
    k = np.array(list(dic.keys()))
    v = np.array(list(dic.values()))

    # Get argsort indices
    sidx = k.argsort()

    # Drop the magic bomb with searchsorted to get the corresponding
    # places for a in keys (using sorter since a is not necessarily sorted).
    # Then trace it back to original order with indexing into sidx
    # Finally index into values for desired output.
    return v[sidx[np.searchsorted(k,ar,sorter=sidx)]]

CanvasTest = np.zeros((6,6), dtype=int).reshape(6,6)
CanvasTest[1,1:5] = [1,1,1,1]
print(CanvasTest)
print(publish(CanvasTest))

op = "\n......\n.xxxx.\n......\n......\n.....\n......"

print("\r\nbreak \r\n"+op +"\r\n")

assert(publish(CanvasTest) == op)


[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
......
.xxxx.
......
......
......
......

break 

......
.xxxx.
......
......
.....
......



AssertionError: ignored

In [153]:
import unittest	

def drawLine(Canvas,x1,y1,x2,y2,maskDigit):
    ## Write Validation of Canvas.shape and x1,x2,x3,x4 being within bounds
    if (y1 == y2): 
        ##Return a new 1D array of given shape and type, filled with ones.
        ## Using command  np.ones((x2-x1+1,), dtype=int) 
        ##Using '1' to draw line i.e x2-x1+1 and hence updating entries for columns on a given row
        Canvas[y1, x1:x2+1] = np.ones((x2-x1+1,), dtype=int)*maskDigit ## e.g. Represents [1,1,1,1] if x2-x1+1 = 4
    elif(x1 == x2): 
        ##Return a new 1D array of given shape and type, filled with ones.
        ## Using command  np.ones((y2-y1+1,), dtype=int) 
        ##Using '1' to draw line i.e y2-y1+1 and hence updating entries for rows on a given column
        Canvas[y1:y2+1, x1] = np.ones((y2-y1+1,), dtype=int)*maskDigit  ## e.g. Represents [1,1,1,1] if y2-y1+1 = 4
    else:
        print('Cant draw a diagonal(out of scope)')
    return Canvas



# Empty Array
arr0 = np.zeros((6,6), dtype=int).reshape(6,6)

#Hypothetical Output Array
arr2 = np.zeros((6,6), dtype=int).reshape(6,6)
arr2[1,1:5] = [1,1,1,1]
print(arr2)
print('\n')

#Testing drawLine 
arr1 = drawLine(arr0,1,1,4,1,maskDigit=1)
print(arr1)
print('\n')

try:
    np.testing.assert_array_equal(arr1, arr2)
    res = True
except AssertionError as err:
    res = False
    print(err)

unittest.TestCase.assertTrue(res, True)
print('DrawLine:TEST1: Successfully Passed')

[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


DrawLine:TEST1: Successfully Passed


Testing DrawLine-Horizontal
DrawLine-Horizontal Any Assertions ? = None
-----test1 Passed----
Testing DrawLine-Vertical
DrawLine-Vertical Any Assertions ? = None
-----test2 Passed----
Not Diagonal Inputs
DrawLine-Diagonal Any Assertions ? = None
-----test3 Passed----
Testing DrawRectangle
DrawRectangle Any Assertions ? = None
-----test4 Passed----
