<a href="https://colab.research.google.com/github/wizlearner/vanna/blob/master/ASCII_Canvas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Problem Statement

*** The Problem ***

__Description__

You're given the task of writing a simple console version of a drawing program.
At this time, the functionality of the program is quite limited but this might change in the future.
In a nutshell, the program should work as follows:
 1. Create a new canvas
 2. Create
 3. Quit
Command 		Description
C w h           Should create a new canvas of width w and height h.
L x1 y1 x2 y2   Should create a new line from (x1,y1) to (x2,y2). Currently only
                horizontal or vertical lines are supported. Horizontal and vertical lines
                will be drawn using the 'x' character.
R x1 y1 x2 y2   Should create a new rectangle, whose upper left corner is (x1,y1) and
                lower right corner is (x2,y2). Horizontal and vertical lines will be drawn
                using the 'x' character.
B x y c         Should fill the entire area connected to (x,y) with "colour" c. The
                behavior of this is the same as that of the "bucket fill" tool in paint
                programs.
Q               Should quit the program.

__Sample I/O__

Below is a sample run of the program. User input is prefixed with enter command:



![alt text](https://drive.google.com/open?id=1f95UvF_ZkzZ_xvvzeE7wRxdrf9pC6_i6) Output


## Solution

##*italicized text* Pseudo Code

(i) Create Canvas class: Handle drawing different primitives like pixel, line, rectangle and do a bucket fill. 

(ii) Implement reading commands from console and apply them on a canvas.

(iii) Then print out the canvas on each command.

## Input validation (Don't let the user input invalid values.) 

(i) If your canvas starts at 1, 0 and below should be invalid. 

(ii) And Bucket fill should notify the user in case they fill directly on a line (or outside the canvas).

(iii) Also check if too many or too few arguments were supplied.

Command Line Parser | Validation Support
    ##### HARD Validation Type
          # No Input on CLS Error:Command NotFound
          ## cmdLength !=[3,5,1] Error:Incomplete Command
          ### cmdType !=[C,L,R,B,Q] Error:Invalid I/O
    ##### SOFT Validation Type
          # C w h [w,h]!=Int Err:Coordinates/Require Num  
          ## L x y a b CHECK y=b Error: y=b 
          ### R x y a b CHECK x!=a and y!=b 

(iv) Trick to draw the 

(v) Start drawing on the canvas by issuing various commands

(vi) Can the codebased evolve with new requirements

(vii) Testing Cases Class has to be added

(viii) Package in an API/Docker Image Distributable





In [66]:
import re
import numpy as np

# Set an initial condition.
game_active = True

#define helper functions
def drawCanvasCMD(cmdType):
        print('Inside drawCanvas' +cmdType)
        if cmdType =='C': 
          return 'drawCanvas'
        else:
          return 'invalid'  

def fillBucketCMD(cmdType):
        print('Inside fillBucket' + cmdType)
        print(cmdType)
        if cmdType =='B':
          return 'fillBucket'
        else:
          return 'Invalid Command' 

def drawLineOrRectangleCMD(cmdType):
        print('Inside drawLineOrRectangleOrfillBucket' + cmdType)
        print(cmdType)
        if cmdType =='L':
          return 'drawLine'
        elif cmdType =='R':
          return 'drawRectangle'
        else:
          return 'Invalid Command' 

def noCommandOrQuittingCMD(cmdType):
        print('Inside noCommandOrQuitting' +cmdType)
        if cmdType =='Q':
          return False
        elif cmdType == ' ':
          return 'No Command'
        else:
          return 'Invalid Command' 

def noInputCMD(cmdType):
        print('Inside noInput' +cmdType)
        if cmdType == '':
          return 'Nothing entered'
        else:
          return 'Invalid Command'

def inCompleteCMD(cmdType):
        print('Inside inComplete' +cmdType)
        return 'No Such Command'


def commandValidation(i,cmdType):
        switcher={
                0:noInputCMD,
                1:noCommandOrQuittingCMD,
                2:inCompleteCMD,
                3:drawCanvasCMD,
                4:fillBucketCMD,
                5:drawLineOrRectangleCMD,
                6:lambda:'anything'
                }
        func=switcher.get(i,lambda :'Invalid')
        return func(cmdType)

def drawLine(Canvas,x1,y1,x2,y2, maskDigit):
    ## Write Validation of Canvas.shape and x1,x2,x3,x4 being within bounds
    if (y1 == y2): 
        ##Return a new 1D array of given shape and type, filled with ones.
        ## Using command  np.ones((x2-x1+1,), dtype=int) 
        ##Using '1' to draw line i.e x2-x1+1 and hence updating entries for columns on a given row
        Canvas[y1, x1:x2+1] = np.ones((x2-x1+1,), dtype=int)*maskDigit ## e.g. Represents [1,1,1,1] if x2-x1+1 = 4
    elif(x1 == x2): 
        ##Return a new 1D array of given shape and type, filled with ones.
        ## Using command  np.ones((y2-y1+1,), dtype=int) 
        ##Using '1' to draw line i.e y2-y1+1 and hence updating entries for rows on a given column
        Canvas[y1:y2+1, x1] = np.ones((y2-y1+1,), dtype=int)*maskDigit  ## e.g. Represents [1,1,1,1] if y2-y1+1 = 4
    else:
        print('Cant draw a diagonal(out of scope)')
    return Canvas

def drawRect(Canvas,x1,y1,x2,y2,maskDigit):
    drawLine(Canvas,x1,y1,x1,y2,maskDigit) 
    drawLine(Canvas,x2,y1,x2,y2,maskDigit)
    drawLine(Canvas,x1,y1,x2,y1,maskDigit)
    drawLine(Canvas,x1,y2,x2,y2,maskDigit)
    return Canvas

def drawHorizontalPadding(Canvas,x1,y1,x2,y2,maskDigit):
    #Horizontal Padding with '-'
    drawLine(Canvas,0,0,y2-1,0,maskDigit)
    drawLine(Canvas,0,x2-1,y2-1,x2-1,maskDigit)
    return Canvas
    
def drawVerticalPadding(Canvas,x1,y1,x2,y2,maskDigit):
    #Vertical Padding with '|'
    drawLine(Canvas,0,1,0,x2-2,maskDigit) 
    drawLine(Canvas,y2-1,1,y2-1,x2-2,maskDigit)
    return Canvas    

def replace_with_dict(ar, dic):
    # Extract out keys and values
    k = np.array(list(dic.keys()))
    v = np.array(list(dic.values()))

    # Get argsort indices
    sidx = k.argsort()

    # Drop the magic bomb with searchsorted to get the corresponding
    # places for a in keys (using sorter since a is not necessarily sorted).
    # Then trace it back to original order with indexing into sidx
    # Finally index into values for desired output.
    return v[sidx[np.searchsorted(k,ar,sorter=sidx)]]

def fillBucket(Canvas, x, y, targetDigit, maskDigit):
    # Use the Canvas 2D array and check if the oldDigit at x, y needs to be replacesd
    # The recursive algorithm. Starting at x and y, changes any adjacent
    # digits that match targetDigit to newDigit.
    canvasWidth = len(Canvas)
    canvasHeight = len(Canvas[0])
    
    if targetDigit == None:
        targetDigit = Canvas[x][y]

    # Base case. If the current x, y digit is not the targetDigit,
    # then do nothing.
    if Canvas[x][y] != targetDigit:
        return 
    
    # Change the digit at Canvas[x][y] to newDigit 
    Canvas[x][y] = maskDigit

    # Recursive calls. Make a recursive call as long as we are not on the
    # boundary (which would cause an Index Error.)
    if x > 0: # left
        fillBucket(Canvas, x - 1, y, targetDigit, maskDigit)
    if y > 0: # up
        fillBucket(Canvas, x, y - 1, targetDigit, maskDigit) 
    if x < canvasWidth-1: # right
        fillBucket(Canvas, x + 1, y, targetDigit, maskDigit)
    if y < canvasHeight-1: # down
        fillBucket(Canvas, x, y + 1, targetDigit, maskDigit)
    return Canvas

def publish(Canvas):
    transdict = {'8': '-', '9': '|', '1': 'x','0':' ','5':'o'} #Translation Dictionary
    chars_ascii = replace_with_dict(Canvas.astype(str),transdict)
    strings_f = chars_ascii.view('U' + str(chars_ascii.shape[1])).flatten()  
    return print( "\n".join(strings_f))



# Set up the while loop.
while game_active:
    # Run the game.
    # At some point, the game ends and game_active will be set to False.
    # When that happens, the loop will stop executing.

    # Get some input from the user.
    command = input('enter command: ')
    # This is the command input taken the user
    commandList = (re.split(r'\s',command)) # Separate string by spaces i.e '\s' expression
    print(commandList) 
    print(len(commandList))
    #Empty string Validation needs to be handled as command="" edge case is giving length = 1
    cmdType = commandList[0]
    game_active = commandValidation(len(commandList),cmdType)
    
    ## START OF MAIN PROGRAM
    if game_active == 'drawCanvas':
        # Create an Empty 2D Array
          row = int(commandList[1])+2
          col = int(commandList[2])+2
          Canvas1 = np.zeros((row,col), dtype=int).reshape(row,col)

          ##drawPadding: i.e '----' and '|' on borders. This is a special case of drawRect with edge cases
          ##If user demands 10x16 canvas then 12x18 has be designed to accomodate borders padding
          Canvas1 = drawHorizontalPadding(Canvas1,0,0,row,col,maskDigit=8)
          Canvas1 = drawVerticalPadding(Canvas1,0,0,row,col,maskDigit=9)
          publish(Canvas1)
    elif game_active == 'drawLine':
          #L 1 3 4 3 [Line Movement on a given Row] OR #L 2 1 2 4 [Line Movement on a given Column]
          ## e.g. L 1 3 4 3 #(x1,x2) = (1,4) & (y1,y2)= (3,3) [On Row 3 draw a line covering 4-1+1 = 4places] = WalkType = AlongRow
          x1,y1 = int(commandList[1]), int(commandList[2])
          x2,y2 = int(commandList[3]), int(commandList[4])
          Canvas1 = drawLine(Canvas1,x1,y1,x2,y2,maskDigit=1) #Using maskDigit=1 means mask by 1 in 2D array
          publish(Canvas1)
    elif game_active == 'drawRectangle':
          x1,y1 = int(commandList[1]), int(commandList[2])
          x2,y2 = int(commandList[3]), int(commandList[4])
          #R 1 5 6 7[Draw a Rectangle between (1,5) and (6,7)]
          ##Essentially it means draw 4 lines i.e [L 1 5 1 7] [L 6 5 6 7] [L 1 5 6 5] [L 1 7 6 7]
          Canvas1 = drawRect(Canvas1,x1,y1,x2,y2,maskDigit=1)
          publish(Canvas1)
    elif game_active == 'fillBucket':
          x,y = int(commandList[1]), int(commandList[2])
          print('TIME TO PAINT THE BUCKET')
          Canvas1 = fillBucket(Canvas1, x, y, 0, maskDigit=5)
          publish(Canvas1) 
    else:
         print('YOUR INPUT IS INVALID TRY AGAIN OR PRESS Q TO EXIT')     

# Do anything else you want done after the loop runs.
print("\nOh no, you decided to QUIT call coins collected = 0! Game Over.")

enter command: C 20 40
['C', '20', '40']
3
Inside drawCanvasC
------------------------------------------
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
|                                        |
-----------------------------------

## FUNNNNN.... :Text to ASCII Art

In [0]:
# !pip install pyfiglet
import pyfiglet

In [0]:
ascii_banner = pyfiglet.figlet_format("VANNA!!")
print(ascii_banner) 


__     ___    _   _ _   _    _    _ _ 
\ \   / / \  | \ | | \ | |  / \  | | |
 \ \ / / _ \ |  \| |  \| | / _ \ | | |
  \ V / ___ \| |\  | |\  |/ ___ \|_|_|
   \_/_/   \_\_| \_|_| \_/_/   \_(_|_)
                                      



## FUNNNN....Turtle - Turtle graphics for Tk 
https://docs.python.org/2/library/turtle.html

In [0]:
## Turtle for Google Colab notebooks Installation for Google Colab
# !pip3 install ColabTurtle
from ColabTurtle.Turtle import *

In [0]:
# Make a Square   
initializeTurtle(initial_speed=2)
bgcolor('white')
color('green')

width (30)
forward(100)
right(90)
forward(100)
right(90)
forward(100)
right(90)
forward(100)
right(90)

width (15)
setx (20)
sety(40)
goto(200,100)

right(90)
forward(50)
left(90)
forward(50)
hideturtle()
showturtle()



In [0]:
# Draw a Complex Shape 
initializeTurtle(initial_speed=10)
color('orange')
bgcolor('white')
width(1)
for i in range(36):
    forward(200)
    left(170)

In [0]:
# Draw a Tree

initializeTurtle(initial_speed=10)
color('white')
bgcolor('black')

min_length=20

def draw_branch(l, w):
  left(15)
  draw_stick(l, w)
  right(30)
  draw_stick(l, w)
  left(15)
  
def draw_stick(l, w):
  width(w)
  forward(l)
  if min_length < l:
    draw_branch(math.ceil(l*0.8), math.ceil(w*0.6))
  backward(l)

penup()
sety(470)
pendown()
draw_branch(100, 10)

In [0]:
# User selects which shape to Draw [Triangle/Square]
initializeTurtle(initial_speed=10)
def draw(running, entered):
  initializeTurtle(initial_speed=10)
  while running:
    if entered == 'triangle':
      for i in range(3):
        forward(100)
        right(120)  
      running = False
    elif entered == 'square':
      for i in range(4):
        forward(100)
        right(90)
      running = False
    elif entered == 'exit':
      running = False
      print('exiting...')

    else:
      print('not a command')
  
  
  print('bye!')
  
print('enter triangle, square, or exit:') #supported inputs = {triangle, square, exit}
draw(True, input()) 

In [0]:
initializeTurtle(initial_speed=10)
x1, y1, x2, y2 = 10, 20, 30, 40
color('white')
bgcolor('black')


# ROUGH WORK CLI Based Drawing Canvas

## Type1: Command Prompt Parser

In [135]:
import re
xx = "L 4 5 6 8"
yy = input()
#r1 = re.findall(r"""[Cc]\s+(\d+)\s+(\d+)""",xx)
#print(r1)


commandList = (re.split(r'\s',xx)) # Separate string by spaces i.e '\s' expression
print(commandList) 
length = len(commandList)
print(length)
#Empty string Validation needs to be handled as xx="" edge case is giving length = 1

def drawCanvas(cmdType):
        print('Inside drawCanvas' +cmdType)
        if cmdType =='C':
          return 'drawCanvas'
        else:
          return 'Invalid'  

def drawLineOrRectangleOrfillBucket(cmdType):
        print('Inside drawLineOrRectangleOrfillBucket' + cmdType)
        print(cmdType)
        if cmdType =='L':
          return 'drawLine'
        elif cmdType =='R':
          return 'drawRectangle'
        elif cmdType =='B':
          return 'fillBucket'  
        else:
          return 'Invalid Command' 

def noCommandOrQuitting(cmdType):
        print('Inside noCommandOrQuitting' +cmdType)
        if cmdType =='Q':
          return 'quitting'
        elif cmdType == ' ':
          return 'No Command'
        else:
          return 'Invalid Command' 

def noInput(cmdType):
        print('Inside noInput' +cmdType)
        if cmdType == '':
          return 'Nothing entered'
        else:
          return 'Invalid Command'

def inComplete(cmdType):
        print('Inside inComplete' +cmdType)
        return 'No Such Command'


def commandValidation(i,cmdType):
        switcher={
                0:noInput,
                1:noCommandOrQuitting,
                2:inComplete,
                3:drawCanvas,
                4:inComplete,
                5:drawLineOrRectangleOrfillBucket,
                6:lambda:'anything'
                }
        func=switcher.get(i,lambda :'Invalid')
        return func(cmdType)

commandValidation(len(commandList),commandList[0])

C 4 5 6 7
['L', '4', '5', '6', '8']
5
Inside drawLineOrRectangleOrfillBucketL
L


'drawLine'

## Type2: Command Prompt Parser 

In [137]:

method =['Nothing,Canvas,Line,Rectangle,FillBucket,Quit','Inavlid']

class Switcher(object):
          def commandLength(self,i):
                   method_name='draw'+str(i)
                   method=getattr(self,method_name,lambda :'Invalid')
                   return method()
          def draw0(self):
                   return 'Nothing'
          def draw1(self):
                   return 'Incomplete Input'
          def draw2(self):
                   return 'Incomplete Input'
          def draw3(self):
                   return 'draw empty Canvas'
          def draw4(self):
                   return 'Incomplete Input'
          def draw5(self): 
                   return 'draw Line/Rectangle/FillBucket'
          def draw6(self): 
                   return 'Undefined command of greater than size 6'

s= Switcher()
s.commandLength(len(commandList))                 

'draw Line/Rectangle/FillBucket'

## Pattern Matching using RegEx


In [95]:
import re

list = ["guru99 get", "guru99 give", "guru Selenium"]
for element in list:
    z = re.match("(g\w+)\W(g\w+)", element)
if z:
    print((z.groups()))
    
patterns = ['software testing', 'guru99']
text = 'software testing is fun?'
for pattern in patterns:
    print('Looking for "%s" in "%s" ->' % (pattern, text), end=' ')
    if re.search(pattern, text):
        print('found a match!')
else:
    print('no match')
abc = 'guru99@google.com, careerguru99@hotmail.com, users@yahoomail.com'
emails = re.findall(r'[\w\.-]+@[\w\.-]+', abc)
for email in emails:
    print(email)

Looking for "software testing" in "software testing is fun?" -> found a match!
Looking for "guru99" in "software testing is fun?" -> no match
guru99@google.com
careerguru99@hotmail.com
users@yahoomail.com


## Character to Pixel using Numpy

In [42]:

from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw
import numpy as np

text = "SEXY"
path = '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'
font = ImageFont.truetype(path, 12)

size = font.getsize(text)
img = Image.new("1",size,"black")
draw = ImageDraw.Draw(img)
print(draw)
draw.text((0, 0), text, "white", font)
print(img)
pixels = np.array(img, dtype=np.uint8)
'''numerical data arranged in an array-like structure in Python can 
be converted to arrays through the use of the array() function. 
The most obvious examples are lists and tuples'''
print(pixels)
chars = np.array([' ','#'], dtype="U1")[pixels]
print(chars)
'''VIEW: If you update elements of original array the view(snapshot also
    gets automatically updated'''

strings = chars.view('U' + str(chars.shape[1])).flatten()


''' https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html
Flatten the View i.e A copy of the input array, flattened to one dimension
'''

print( "\n".join(strings))

<PIL.Image.Image image mode=1 size=33x11 at 0x7FA40BF6F358>
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0]
 [0 1 1 0 0 0 1 0 0 1 1 0 0 1 0 0 1 1 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0]
 [0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 0 1 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0]
 [0 0 1 1 1 1 0 0 0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 1 1 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0]
 [0 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 1 1 0 0 0 0]]
[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '
  ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '

## Character to Pixel A-Z Letters


In [4]:
from __future__ import print_function
import string
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw
import numpy as np

def char_to_pixels(text, path='arialbd.ttf', fontsize=14):
    """
    Based on https://stackoverflow.com/a/27753869/190597 (jsheperd)
    """
    font = ImageFont.truetype(path, fontsize) #load the font
    w, h = font.getsize(text)  #calc the size of text in pixels
    h *= 2 
    image = Image.new('L', (w, h), 1)  #create a b/w image
    draw = ImageDraw.Draw(image)
    draw.text((0, 0), text, font=font) #render the text to the bitmap
    arr = np.asarray(image)
    arr = np.where(arr, 0, 1)
    arr = arr[(arr != 0).any(axis=1)]
    return arr

def display(arr):
    result = np.where(arr, '#', ' ')
    print('\n'.join([''.join(row) for row in result]))

for c in string.ascii_uppercase:
    arr = char_to_pixels(
        c, 
        path='/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf', 
        fontsize=9)
    print(arr.shape)
    display(arr)
    print()

(7, 7)
  ##   
  ##   
   ##  
 #  #  
 ####  
    ## 
##  ## 

(7, 6)
##### 
 #  # 
 #  # 
 #### 
 #  ##
 #  ##
##### 

(7, 7)
  #### 
 ##    
 #     
##     
 #     
 ##    
  #### 

(7, 7)
#####  
 #  ## 
 #  ## 
 #   # 
 #   # 
 #  ## 
#####  

(7, 6)
##### 
 #    
 #    
 ###  
 #    
 #    
##### 

(7, 6)
##### 
 #    
 #    
 ###  
 #    
 #    
###   

(7, 7)
  #### 
 ##  # 
 #     
##     
 #  ###
 ##  # 
  #### 

(7, 7)
### ###
 #   # 
 #   # 
 ##### 
 #   # 
 #   # 
### ###

(7, 4)
### 
 #  
 #  
 #  
 #  
 #  
### 

(7, 5)
  ## 
  ## 
  ## 
  ## 
  ## 
  #  
###  

(7, 7)
###  # 
 #  #  
 # #   
 ###   
 # ##  
 #  ## 
###  ##

(7, 6)
###   
 #    
 #    
 #    
 #    
 #   #
##### 

(7, 9)
###   ## 
 ##  ##  
  #   #  
  ##  #  
   ## #  
   #  #  
## # ### 

(7, 7)
### ## 
 ##  # 
 ### # 
  #### 
   ### 
    ## 
##   # 

(7, 7)
  ###  
 #   # 
 #   # 
##   ##
 #   # 
 #   # 
  ###  

(7, 6)
##### 
 #  # 
 #  # 
 #### 
 #    
 #    
###   

(9, 7)
  ###  
 #   # 
 #   # 
#

In [20]:
import numpy as np
X = np.array([[135,30],[35,40],[75,40]])
print(X)
print('Prin------')
Y= X[0,0:2]
print(Y)
print('------')
Z = X[0:2,0]
print(Z)

[[135  30]
 [ 35  40]
 [ 75  40]]
Prin------
[135  30]
------
[135  35]


##Printing Characters ['-', '|', '@']

In [29]:
loop = [1,2,3,4,5,6,7]

print('-'*10)
print('|'*5)
print('@'*3)

for i in loop:
    print('-') 


for i in loop:
    print('|') 

----------
|||||
@@@
@
@
@
@
@
@
@
|
|
|
|
|
|
|


In [33]:

canvas_w = [1,2,3]
canvas_h = [1,2,3,4,5]
''' Determining the Position in 2-D matrix e.g. 3,5 '''

for x in canvas_h: 
    print('@')
    for y in canvas_w:
      print('@'*y)




@
@
@@
@@@
@
@
@@
@@@
@
@
@@
@@@
@
@
@@
@@@
@
@
@@
@@@


In [35]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

## 2D Numpy Array to Desired Output

In [80]:
import numpy as np
## pixels_01 = np.array([[0,1,0,1,1,1,0],[0,0,0,1,1,0,1],[0,0,0,1,1,0,1],[0,0,0,1,1,0,1]])


canvas_w=3
canvas_h=4


## Generating an array of random integers, declaring & populating 2D array
pixels_01 = np.random.randint(0,2, size=(canvas_w+2,canvas_h+2))
## After adding canvas_w+2,canvas_h+2 we are able to accomdate a border of canvas

## Filling border pads with horizontal '-' and vertical ='|' as directed

print(pixels_01)
print('-------Break-----')
chars_ascii = np.array([' ','#'], dtype="U1")[pixels_01]
print(chars_ascii)
strings_f = chars_ascii.view('U' + str(chars_ascii.shape[1])).flatten()
print('-------Break-----')
print( "\n".join(strings_f))

print('-------Break-----')
print('-------Manually Refilling the Bucket-----')
## Rerun After Manually Refilling the Full Bucket

##pixels_01 = np.array([[1,1,1,1,1,1,1],[1,1,1,1,1,1,1],[1,1,1,1,1,1,1],[1,1,1,1,1,1,1]])
pixels_01 = np.random.randint(1,2, size=(4,8))
chars_ascii = np.array([' ','#'], dtype="U1")[pixels_01]
strings_f = chars_ascii.view('U' + str(chars_ascii.shape[1])).flatten()
print( "\n".join(strings_f))



[[1 0 1 1 1 1 0 1]
 [0 0 0 0 1 1 0 1]
 [1 1 1 1 1 1 1 0]
 [1 1 0 0 1 0 1 1]]
-------Break-----
[['#' ' ' '#' '#' '#' '#' ' ' '#']
 [' ' ' ' ' ' ' ' '#' '#' ' ' '#']
 ['#' '#' '#' '#' '#' '#' '#' ' ']
 ['#' '#' ' ' ' ' '#' ' ' '#' '#']]
-------Break-----
# #### #
    ## #
####### 
##  # ##
-------Break-----
-------Manually Refilling the Bucket-----
########
########
########
########


## Reshape a new 1D array into 2D r x c array

In [84]:
# reshape a shape-(24,) array into a shape-(2,3,4) array
np.arange(2*3*4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [90]:
np.arange(2*3*4).reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [93]:
##Canvas requested 3x4--->after Padding--->becomes 5x6
np.arange(5*6)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## Manual Trial Run of Drawing a Line

In [10]:
#L 1 3 4 3 [Line Movement on a given Row]
a = np.arange(8*9).reshape(8,9)

COLi = 1
COLj = 4
ROW = 3
#MoveForward: Replace '0s' with '1'


##Return a new array of given shape and type, filled with ones.
array_ones = np.ones((COLj-COLi+1,), dtype=int) ## e.g. Represents [1,1,1,1] if COLj-COLi+1 = 4
##Using '1' to represent forward traversal and hence updating entries
a[ROW, COLi:COLj+1] = array_ones  
print(a)

print('---BREAK---')

b = np.arange(8*9).reshape(8,9) ## Canvas 6x7
#L 2 1 2 4 [Line Movement on a given Column]
ROWi = 1
ROWj = 4
COL = 2
#MoveForward: Replace '0s' with '1'
b[ROWi:ROWj+1, COL ] =  np.ones((ROWj,), dtype=int) ## [1,1,1]
b
print(b)


print('---CHECKING Transpose of a 2D matrix to leverage same code---')
c = np.transpose(a)

##Return a new array of given shape and type, filled with ones.
array_ones_c = np.ones((COLj-COLi+1,), dtype=int) ## e.g. Represents [1,1,1,1] if COLj-COLi+1 = 4
##Using '1' to represent forward traversal and hence updating entries
c[ROW, COLi:COLj+1] = array_ones_c  
print(np.transpose(c))

#We have proven transposing works for Horizontal/Vertical Function. Hence we leverage a standard function 

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27  1  1  1  1 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]
---BREAK---
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10  1 12 13 14 15 16 17]
 [18 19  1 21 22 23 24 25 26]
 [27 28  1 30 31 32 33 34 35]
 [36 37  1 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]
---CHECKING Transpose of a 2D matrix to leverage same code---
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11  1 13 14 15 16 17]
 [18 19 20  1 22 23 24 25 26]
 [27  1  1  1  1 32 33 34 35]
 [36 37 38  1 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]


##Polished Function Calls [Line, Rectangle, Publishing]

In [61]:

import numpy as np

def drawLine(Canvas,x1,y1,x2,y2,maskDigit):
    ## Write Validation of Canvas.shape and x1,x2,x3,x4 being within bounds
    if (y1 == y2): 
        ##Return a new 1D array of given shape and type, filled with ones.
        ## Using command  np.ones((x2-x1+1,), dtype=int) 
        ##Using '1' to draw line i.e x2-x1+1 and hence updating entries for columns on a given row
        Canvas[y1, x1:x2+1] = np.ones((x2-x1+1,), dtype=int)*maskDigit ## e.g. Represents [1,1,1,1] if x2-x1+1 = 4
    elif(x1 == x2): 
        ##Return a new 1D array of given shape and type, filled with ones.
        ## Using command  np.ones((y2-y1+1,), dtype=int) 
        ##Using '1' to draw line i.e y2-y1+1 and hence updating entries for rows on a given column
        Canvas[y1:y2+1, x1] = np.ones((y2-y1+1,), dtype=int)*maskDigit  ## e.g. Represents [1,1,1,1] if y2-y1+1 = 4
    else:
        print('Cant draw a diagonal(out of scope)')
    return Canvas


def drawRect(Canvas,x1,y1,x2,y2,maskDigit):
    drawLine(Canvas,x1,y1,x1,y2,maskDigit) 
    drawLine(Canvas,x2,y1,x2,y2,maskDigit)
    drawLine(Canvas,x1,y1,x2,y1,maskDigit)
    drawLine(Canvas,x1,y2,x2,y2,maskDigit)
    return Canvas

def drawHorizontalPadding(Canvas,x1,y1,x2,y2,maskDigit):
    #Horizontal Padding with '-'
    drawLine(Canvas,0,0,y2-1,0,maskDigit)
    drawLine(Canvas,0,x2-1,y2-1,x2-1,maskDigit)
    return Canvas
    
def drawVerticalPadding(Canvas,x1,y1,x2,y2,maskDigit):
    #Vertical Padding with '|'
    drawLine(Canvas,0,1,0,x2-2,maskDigit) 
    drawLine(Canvas,y2-1,1,y2-1,x2-2,maskDigit)
    return Canvas    

def replace_with_dict(ar, dic):
    # Extract out keys and values
    k = np.array(list(dic.keys()))
    v = np.array(list(dic.values()))

    # Get argsort indices
    sidx = k.argsort()

    # Drop the magic bomb with searchsorted to get the corresponding
    # places for a in keys (using sorter since a is not necessarily sorted).
    # Then trace it back to original order with indexing into sidx
    # Finally index into values for desired output.
    return v[sidx[np.searchsorted(k,ar,sorter=sidx)]]

def publish(Canvas):
    transdict = {'8': '-', '9': '|', '1': 'x','0':'.','5':'o'} #Translation Dictionary
    chars_ascii = replace_with_dict(Canvas.astype(str),transdict)
    strings_f = chars_ascii.view('U' + str(chars_ascii.shape[1])).flatten()  
    return print( "\n".join(strings_f))

def fillBucket(Canvas, x, y, targetDigit, newDigit):
    # Use the Canvas 2D array and check if the oldDigit at x, y needs to be replacesd
    # The recursive algorithm. Starting at x and y, changes any adjacent
    # digits that match targetDigit to newDigit.
    canvasWidth = len(Canvas)
    canvasHeight = len(Canvas[0])
    
    if targetDigit == None:
        targetDigit = Canvas[x][y]

    # Base case. If the current x, y digit is not the targetDigit,
    # then do nothing.
    if Canvas[x][y] != targetDigit:
        return 
    
    # Change the digit at Canvas[x][y] to newDigit 
    Canvas[x][y] = newDigit

    # Recursive calls. Make a recursive call as long as we are not on the
    # boundary (which would cause an Index Error.)
    if x > 0: # left
        fillBucket(Canvas, x - 1, y, targetDigit, newDigit)
    if y > 0: # up
        fillBucket(Canvas, x, y - 1, targetDigit, newDigit) 
    if x < canvasWidth-1: # right
        fillBucket(Canvas, x + 1, y, targetDigit, newDigit)
    if y < canvasHeight-1: # down
        fillBucket(Canvas, x, y + 1, targetDigit, newDigit)
    return Canvas


## START OF MAIN PROGRAM

# Create an Empty 2D Array
Canvas1 = np.zeros((12,18), dtype=int).reshape(12,18)

print(Canvas1)
print('---BREAK0---')
##drawPadding: i.e '----' and '|' on borders. This is a special case of drawRect with edge cases
##If user demands 10x16 canvas then 12x18 has be designed to accomodate borders padding
Canvas1 = drawHorizontalPadding(Canvas1,0,0,12,18,maskDigit=8)
print(Canvas1)
print('---BREAK1---')

Canvas1 = drawVerticalPadding(Canvas1,0,0,12,18,maskDigit=9)
print(Canvas1)
print('---BREAK2---')
#L 1 3 4 3 [Line Movement on a given Row]
#(x1,x2) = (1,4) & (y1,y2)= (3,3) [On Row 3 draw a line covering 4-1+1 = 4places] = WalkType = AlongRow
Canvas1 = drawLine(Canvas1,1,3,4,3,scalar=1)
#L 2 1 2 4 [Line Movement on a given Column]
#(y1,y2) = (1,4) & (x1,x2)= (2,2)[On COL 2 draw a line covering 4-1+1 = 4places] = WalkType = AlongCol
print(Canvas1)
print('---BREAK3---')
Canvas1 = drawLine(Canvas1,2,1,2,4,maskDigit=1)
#R 1 5 6 7[Draw a Rectangle between (1,5) and (6,7)]
##Essentially it means draw 4 lines i.e [L 1 5 1 7] [L 6 5 6 7] [L 1 5 6 5] [L 1 7 6 7]
print(Canvas1)
print('---BREAK4---')
Canvas1 = drawRect(Canvas1,1,5,6,7,maskDigit=1)
print(Canvas1)
print('---BREAK5---')

publish(Canvas1)
print('---1st PUBLISH---')

Canvas1 = drawRect(Canvas1,6,6,8,8,maskDigit=1)
print(Canvas1)
print('---2nd PUBLISH---')

publish(Canvas1)


#User Gives Input
x,y = 2,5 ## [Point of Click, taken from user as input]
#Set the Point of Click for 'o' masked by Digit '5' 

## Now fill the Bucket from here with Digit 5
print('---PUBLISH AFTER Fill Bucket--')
publish(fillBucket(Canvas1, x, y, 0, 5))





[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
---BREAK0---


TypeError: ignored

## Fill Bucket Challenge



###Use the Covid Game Example Analogy
https://inventwithpython.com/blog/2011/08/11/recursion-explained-with-the-flood-fill-algorithm-and-zombies-and-cats/


In [0]:
import numpy as np

a = np.zeros((5, 5), dtype=int)
a[1:4, 1:4] = 1
a[2,2] = 0
a
"""array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])"""

ndimage.binary_fill_holes(a).astype(int)
"""array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])"""
# Too big structuring element
ndimage.binary_fill_holes(a, structure=np.ones((5,5))).astype(int)
"""array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])"""